
package mx.doki.dokipos.views;

// @author Andrey

import javax.swing.table.DefaultTableModel;
import mx.doki.dokipos.entities.Usuario;


public class CajaForm extends javax.swing.JDialog {
    
    // Variable global en la vista para recordar quién está cobrando
    private Usuario usuarioCajero;
    
    /**
     * Creates new form CajaForm
     */
    public CajaForm(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.usuarioCajero = usuario; // Guardamos la sesion activa
        
        setTitle("Doki Market - Caja");
        setLocationRelativeTo(null); // Centrar pantalla
        
        // Agregar producto con la tecla Enter
        tfCodigoBarras.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Invoca directamente al evento del boton agregar al pulsar Enter
                btnAgregarActionPerformed(evt);
            }
        });
        
        // Forzar foco inicial cuando la ventana aparezca en pantalla
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                tfCodigoBarras.requestFocusInWindow();
            }
        });

        // Si cualquier elemento del sistema le quita el foco, el cuadro lo reclama al instante
        tfCodigoBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                // Usamos invokeLater para esperar que terminen otros procesos visuales de Swing antes de retomar el foco
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        tfCodigoBarras.requestFocusInWindow();
                    }
                });
            }
        });
        
    }
    
    
    
    /**
    * Recorre todas las filas del JTable, suma los subtotales y refresca el lblTotal
    */
   private void recalcularTotal() {
       DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
       double totalAcumulado = 0.0;
       
       for (int i = 0; i < modelo.getRowCount(); i++) {
           totalAcumulado += Double.parseDouble(modelo.getValueAt(i, 4).toString());
       }
       
       lblTotal.setText("TOTAL: $" + String.format("%.2f", totalAcumulado));
   }
   
   
   
   /**
    * Resetea por completo los componentes para dejar la pantalla lista para otra transaccion
    */
   private void limpiarPantallaVenta() {
       tfCodigoBarras.setText("");
       DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
       modelo.setRowCount(0); // Vacia todas las filas del JTable
       lblTotal.setText("TOTAL: $0.00");
       tfCodigoBarras.requestFocusInWindow();
   }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCodigoBarras = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrito = new javax.swing.JTable();
        btnFinalizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("Escanea o Escribe el Codigo de Barras:");

        tfCodigoBarras.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tfCodigoBarras.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnAgregar.setBackground(new java.awt.Color(51, 153, 255));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tblCarrito.setBackground(new java.awt.Color(153, 204, 255));
        tblCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblCarrito);

        btnFinalizar.setBackground(new java.awt.Color(51, 153, 255));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar Venta");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Artículo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 153, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("TOTAL: $0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Doki Market - Caja");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        String codigo = tfCodigoBarras.getText().trim();
        
        if (codigo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un codigo de barras.", "Doki Market", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Buscar si el producto existe usando el DAO de productos
        mx.doki.dokipos.daos.ProductoDAO productoDAO = new mx.doki.dokipos.daos.ProductoDAO();
        mx.doki.dokipos.entities.Producto p = productoDAO.obtenerPorCodigo(codigo);
        
        if (p == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Producto no encontrado.", "Doki Market", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
        boolean existeEnTabla = false;
        int filaDestino = -1;
        
        // Buscar si el producto ya esta en las filas de la tblCarrito
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 0).toString().equals(p.getCodigoBarras())) {
                existeEnTabla = true;
                filaDestino = i;
                break;
            }
        }
        
        // Validacion de stock disponible
        int cantidadAComprar = 1; // Si es nuevo, pretendemos agregar 1
        if (existeEnTabla) {
            // Si ya esta en la tabla, la cantidad pretendida sera la actual + 1
            int cantidadActual = Integer.parseInt(modelo.getValueAt(filaDestino, 3).toString());
            cantidadAComprar = cantidadActual + 1;
        }

        // Comparamos lo que el cliente quiere llevar contra el stock actual en la Base de Datos
        if (cantidadAComprar > p.getStock()) {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "No hay suficiente stock disponible para: " + p.getNombre() + "\n" +
                "Stock actual: " + p.getStock() + "\n" +
                "Cantidad intentada: " + cantidadAComprar, 
                "Doki Market - Stock Insuficiente", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            tfCodigoBarras.setText("");
            tfCodigoBarras.requestFocus();
            return; // Detiene por completo el flujo y no altera el carrito
        }
        
        if (existeEnTabla) {
            // INCREMENTAR EN +1 CANTIDAD Y AJUSTAR SUBTOTAL
            int cantidadActual = Integer.parseInt(modelo.getValueAt(filaDestino, 3).toString());
            int nuevaCantidad = cantidadActual + 1;
            double subtotalNuevo = p.getPrecioVenta() * nuevaCantidad;

            modelo.setValueAt(nuevaCantidad, filaDestino, 3);
            modelo.setValueAt(subtotalNuevo, filaDestino, 4);
        } else {
            // AGREGAR COMO NUEVO RENGLON
            Object[] nuevaFila = new Object[] {
                p.getCodigoBarras(),
                p.getNombre(),
                p.getPrecioVenta(),
                1, // Cantidad inicial
                p.getPrecioVenta() // Subtotal inicial (Precio * 1)
            }; 
            modelo.addRow(nuevaFila);
        }
        
        tfCodigoBarras.setText("");
        tfCodigoBarras.requestFocus(); // Regresa el cursor para capturar el siguiente
        recalcularTotal();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    
    
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
        DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
        
        if (modelo.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El carrito de compras esta vacio.", "Doki Market", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Armar objeto Venta Maestro
        mx.doki.dokipos.entities.Venta venta = new mx.doki.dokipos.entities.Venta();

        // Limpiamos la cadena del total para extraer solo el valor numerico flotante
        String totalTexto = lblTotal.getText().replace("TOTAL: $", "").replace(",", "");
        double totalVenta = Double.parseDouble(totalTexto);
        venta.setTotal(totalVenta);
        
        if (this.usuarioCajero != null) {
            venta.setUsuario(this.usuarioCajero); // Vincula de forma automatica el ID real
        } else {
            // Proteccion por si acaso corre la vista de forma aislada sin pasar por el login
            mx.doki.dokipos.entities.Usuario respaldo = new mx.doki.dokipos.entities.Usuario();
            respaldo.setId(1);
            venta.setUsuario(respaldo);
        }
        
        // Extraer todos los renglones de la JTable para armar la lista de Detalles
        java.util.List<mx.doki.dokipos.entities.DetalleVenta> detalles = new java.util.ArrayList<>();
        mx.doki.dokipos.daos.ProductoDAO prodDAO = new mx.doki.dokipos.daos.ProductoDAO();
        
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String codigoProd = modelo.getValueAt(i, 0).toString();
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 3).toString());
            double subtotal = Double.parseDouble(modelo.getValueAt(i, 4).toString());
            
            // Recuperamos la entidad del producto para amarrarlo al detalle
            mx.doki.dokipos.entities.Producto p = prodDAO.obtenerPorCodigo(codigoProd);
            
            mx.doki.dokipos.entities.DetalleVenta d = new mx.doki.dokipos.entities.DetalleVenta();
            d.setProducto(p);
            d.setCantidad(cantidad);
            d.setSubtotal(subtotal);
            
            detalles.add(d);
        }
        
        // Invocar al controlador de ventas
        mx.doki.dokipos.controllers.VentaController ventaController = new mx.doki.dokipos.controllers.VentaController();
        String resultado = ventaController.registrarVenta(venta, detalles);
        
        if (resultado.startsWith("Exito:")) {
            javax.swing.JOptionPane.showMessageDialog(this, resultado, "Doki Market - Venta Realizada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            limpiarPantallaVenta(); // Deja la caja lista para el siguiente cliente
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, resultado, "Doki Market - Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed
    
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int filaSeleccionada = tblCarrito.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un articulo del carrito para eliminar.", "Doki Market", javax.swing.JOptionPane.WARNING_MESSAGE);
            tfCodigoBarras.requestFocusInWindow();
            return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblCarrito.getModel();
        int cantidad = Integer.parseInt(modelo.getValueAt(filaSeleccionada, 3).toString());
        double precio = Double.parseDouble(modelo.getValueAt(filaSeleccionada, 2).toString());
        
        if (cantidad > 1) {
            // Solo restamos uno a la cantidad y recalculamos su subtotal
            int nuevaCantidad = cantidad - 1;
            modelo.setValueAt(nuevaCantidad, filaSeleccionada, 3);
            modelo.setValueAt(precio * nuevaCantidad, filaSeleccionada, 4);
        } else {
            // Si solo quedaba uno, removemos por completo la fila completa de la tabla
            modelo.removeRow(filaSeleccionada);
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Articulo eliminado con exito.", "Doki Market", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        recalcularTotal();
        tfCodigoBarras.requestFocusInWindow();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrito;
    private javax.swing.JTextField tfCodigoBarras;
    // End of variables declaration//GEN-END:variables
}
